name: Sample workflow using golang-security-action

on: [push, pull_request]

jobs:
    golang-security-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: ynniss/golang-security-action@v0.1.0-rc
              with:
                CODE_PATH: "."
