name: Sample workflow using golang-security-action

on: []

jobs:
    golang-security-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: ./
              with:
                CODE_PATH: "."
                CONF_PATH: "./gosec-test-conf.json"
