name: Test golang-security-action

on: [push]

jobs:
    golang-security:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: ./
              with:
                CODE_PATH: "/"
